### ISSUE TITLE
Задача 1. Задача по питону.

### ISSUE THREAD

**Issue by cocoscrab** [cocoscrab/best-team-ever#1]
Программа получает на вход список из целых чисел. Ваша задача вывести True в случае, если в данном списке встречается значение 777. В противном случае вывести False

Примечание:

Чтобы прочитать из ввода целые числа и сохранить их в виде списка в переменной my_list вам необходимо написать строчку

my_list = list(map(int, input().split()))

**Comment by grishinaanet** [comment]
Взято в работу

**Comment by grishinaanet** [comment]
готово
